trigger:
- Dev

pool:
  vmImage: ubuntu-latest

jobs:
- job: DeployResources
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Azure subscription 1(ac0949c8-3fd8-4dfb-b492-30a7650c0272)'
      subscriptionId: 'ac0949c8-3fd8-4dfb-b492-30a7650c0272'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'EduShare'
      location: 'East US'
      templateLocation: 'Linked artifact'
      csmFile: 'template.json'  # Relative path within your repository
      csmParametersFile: 'parameters.json'  # Relative path within your repository
      deploymentMode: 'Validation'

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
